[tool.isort]
profile = 'black'

[tool.black]
line-length = 120
target-version = ['py36']
force-exclude = '/tests/'
skip-string-normalization = 'True'

[tool.pytest.ini_options]
norecursedirs = 'examples/*'
addopts = "-s"

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.5.0rc1"
tag_format = "v$version"
